# 网站基本信息
baseURL = "https://blog.7wate.com/"         # 请替换为你的实际域名
languageCode = "zh-cn"
title = "向阳而生"
theme = "typo"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableEmoji = true
canonifyURLs = true

# SEO & 分析
googleAnalytics = "xxx"                        # 生产环境请填入 G-XXXXXX
enableRobotsTXT = true

# 构建性能
timeout = "300s"

# 永久链接结构
[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"

# 自定义分类标签
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"


# 菜单设置
[[params.menu]]
name = "首页"
url = "/"

[[params.menu]]
name = "文辑"
url = "/posts/"

[[params.menu]]
name = "片语"
url = "/memos/"
newTab = true

[[params.menu]]
name = "挚友"
url = "/friend/"
newTab = true

[[params.menu]]
name = "关于"
url = "/about/"
newTab = true

# Typo 主题参数
[params]
description = "一个喜欢异想天开的家伙 💨"
theme = "auto"
colorPalette = "default"
hideHeader = true

# 首页设置
homeIntroTitle = "👋👋👋"
homeIntroContent = """
一个喜欢异想天开的家伙 💨
"""

homeCollectionTitle = "文辑"
homeCollection = "posts"

paginationSize = 7
listSummaries = false
listDateFormat = "2 Jan"

# 页脚设置
showFooter = true
footerContent = "Your **custom** md `footer`"

# 面包屑导航
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "首页"

# Favicon / Logo / SEO 元数据（可选）
# params.logo = "/images/logo.png"
# params.favicon = "/favicon.ico"
# params.keywords = ["技术博客", "分布式系统", "编程", "数据库"]

# 社交链接
# [[params.social]]
# name = "github"
# url = "https://github.com/yourusername"

# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/yourprofile/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@yourusername"

# Markdown 与高亮设置
[markup]
  [markup.highlight]
    style = "algol"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = false  # 更安全，建议通过短代码插入 HTML，而不是直接 HTML

# 安全设置
[security]
  enableInlineShortcodes = true

# 站点地图（SEO）
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# 隐私与 GDPR
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
    disable = false

# 构建压缩设置
[minify]
  minifyOutput = true

# 针对不同构建环境的配置（可选）
[environment.production]
  minifyOutput = true

[environment.development]
  minifyOutput = false
